import { type Registry } from "@/registry/schema";

export const examples: Registry = [
	{
		name: "accordion-demo",
		type: "components:example",
		registryDependencies: ["accordion"],
		files: ["example/accordion-demo.tsx"],
	},
	{
		name: "alert-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-demo.tsx"],
	},
	{
		name: "alert-no-icon-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-no-icon-demo.tsx"],
	},
	{
		name: "alert-error-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-error-demo.tsx"],
	},
	{
		name: "alert-info-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-info-demo.tsx"],
	},
	{
		name: "alert-success-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-success-demo.tsx"],
	},
	{
		name: "alert-warning-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-warning-demo.tsx"],
	},
	{
		name: "avatar-demo",
		type: "components:example",
		registryDependencies: ["avatar"],
		files: ["example/avatar-demo.tsx"],
	},
	{
		name: "avatar-fallback-demo",
		type: "components:example",
		registryDependencies: ["avatar"],
		files: ["example/avatar-fallback-demo.tsx"],
	},
	{
		name: "avatar-size-demo",
		type: "components:example",
		registryDependencies: ["avatar"],
		files: ["example/avatar-size-demo.tsx"],
	},
	{
		name: "badge-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-demo.tsx"],
	},
	{
		name: "badge-destructive-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-destructive-demo.tsx"],
	},
	{
		name: "badge-info-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-info-demo.tsx"],
	},
	{
		name: "badge-outline-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-outline-demo.tsx"],
	},
	{
		name: "badge-secondary-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-secondary-demo.tsx"],
	},
	{
		name: "badge-success-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-success-demo.tsx"],
	},
	{
		name: "badge-unstyled-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-unstyled-demo.tsx"],
	},
	{
		name: "badge-warning-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-warning-demo.tsx"],
	},
	{
		name: "border-group-demo",
		type: "components:example",
		registryDependencies: ["border-group", "button", "menu"],
		files: ["example/border-group-demo.tsx"],
	},
	{
		name: "border-group-horizontal-demo",
		type: "components:example",
		registryDependencies: ["border-group", "button"],
		files: ["example/border-group-horizontal-demo.tsx"],
	},
	{
		name: "border-group-vertical-demo",
		type: "components:example",
		registryDependencies: ["border-group", "button"],
		files: ["example/border-group-vertical-demo.tsx"],
	},
];
