import { type Registry } from "@/registry/schema";

export const examples: Registry = [
	{
		name: "accordion-demo",
		type: "components:example",
		registryDependencies: ["accordion"],
		files: ["example/accordion-demo.tsx"],
	},
	{
		name: "alert-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-demo.tsx"],
	},
	{
		name: "alert-no-icon-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-no-icon-demo.tsx"],
	},
	{
		name: "alert-error-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-error-demo.tsx"],
	},
	{
		name: "alert-info-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-info-demo.tsx"],
	},
	{
		name: "alert-success-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-success-demo.tsx"],
	},
	{
		name: "alert-warning-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-warning-demo.tsx"],
	},
	{
		name: "avatar-demo",
		type: "components:example",
		registryDependencies: ["avatar"],
		files: ["example/avatar-demo.tsx"],
	},
	{
		name: "avatar-fallback-demo",
		type: "components:example",
		registryDependencies: ["avatar"],
		files: ["example/avatar-fallback-demo.tsx"],
	},
	{
		name: "avatar-size-demo",
		type: "components:example",
		registryDependencies: ["avatar"],
		files: ["example/avatar-size-demo.tsx"],
	},
	{
		name: "badge-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-demo.tsx"],
	},
	{
		name: "badge-destructive-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-destructive-demo.tsx"],
	},
	{
		name: "badge-info-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-info-demo.tsx"],
	},
	{
		name: "badge-outline-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-outline-demo.tsx"],
	},
	{
		name: "badge-secondary-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-secondary-demo.tsx"],
	},
	{
		name: "badge-success-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-success-demo.tsx"],
	},
	{
		name: "badge-unstyled-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-unstyled-demo.tsx"],
	},
	{
		name: "badge-warning-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-warning-demo.tsx"],
	},
	{
		name: "border-group-demo",
		type: "components:example",
		registryDependencies: ["border-group", "button", "menu"],
		files: ["example/border-group-demo.tsx"],
	},
	{
		name: "border-group-horizontal-demo",
		type: "components:example",
		registryDependencies: ["border-group", "button"],
		files: ["example/border-group-horizontal-demo.tsx"],
	},
	{
		name: "border-group-vertical-demo",
		type: "components:example",
		registryDependencies: ["border-group", "button"],
		files: ["example/border-group-vertical-demo.tsx"],
	},
	{
		name: "button-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-demo.tsx"],
	},
	{
		name: "button-destructive-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-destructive-demo.tsx"],
	},
	{
		name: "button-disabled-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-disabled-demo.tsx"],
	},
	{
		name: "button-ghost-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-ghost-demo.tsx"],
	},
	{
		name: "button-icon-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-icon-demo.tsx"],
	},
	{
		name: "button-info-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-info-demo.tsx"],
	},
	{
		name: "button-link-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-link-demo.tsx"],
	},
	{
		name: "button-loading-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-loading-demo.tsx"],
	},
	{
		name: "button-outline-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-outline-demo.tsx"],
	},
	{
		name: "button-secondary-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-secondary-demo.tsx"],
	},
	{
		name: "button-success-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-success-demo.tsx"],
	},
	{
		name: "button-warning-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-warning-demo.tsx"],
	},
	{
		name: "calendar-demo",
		type: "components:example",
		registryDependencies: ["calendar"],
		files: ["example/calendar-demo.tsx"],
	},
	{
		name: "calendar-invalid-demo",
		type: "components:example",
		registryDependencies: ["calendar"],
		files: ["example/calendar-invalid-demo.tsx"],
	},
	{
		name: "calendar-range-demo",
		type: "components:example",
		registryDependencies: ["calendar"],
		files: ["example/calendar-range-demo.tsx"],
	},
	{
		name: "calendar-multiple-demo",
		type: "components:example",
		registryDependencies: ["calendar"],
		files: ["example/calendar-multiple-demo.tsx"],
	},
];
