import { type Registry } from "@/registry/schema";

export const examples: Registry = [
	{
		name: "accordion-demo",
		type: "components:example",
		registryDependencies: ["accordion"],
		files: ["example/accordion-demo.tsx"],
	},
	{
		name: "alert-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-demo.tsx"],
	},
	{
		name: "alert-no-icon-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-no-icon-demo.tsx"],
	},
	{
		name: "alert-error-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-error-demo.tsx"],
	},
	{
		name: "alert-info-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-info-demo.tsx"],
	},
	{
		name: "alert-success-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-success-demo.tsx"],
	},
	{
		name: "alert-warning-demo",
		type: "components:example",
		registryDependencies: ["alert"],
		files: ["example/alert-warning-demo.tsx"],
	},
	{
		name: "avatar-demo",
		type: "components:example",
		registryDependencies: ["avatar"],
		files: ["example/avatar-demo.tsx"],
	},
	{
		name: "avatar-fallback-demo",
		type: "components:example",
		registryDependencies: ["avatar"],
		files: ["example/avatar-fallback-demo.tsx"],
	},
	{
		name: "avatar-size-demo",
		type: "components:example",
		registryDependencies: ["avatar"],
		files: ["example/avatar-size-demo.tsx"],
	},
	{
		name: "badge-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-demo.tsx"],
	},
	{
		name: "badge-destructive-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-destructive-demo.tsx"],
	},
	{
		name: "badge-info-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-info-demo.tsx"],
	},
	{
		name: "badge-outline-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-outline-demo.tsx"],
	},
	{
		name: "badge-secondary-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-secondary-demo.tsx"],
	},
	{
		name: "badge-success-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-success-demo.tsx"],
	},
	{
		name: "badge-unstyled-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-unstyled-demo.tsx"],
	},
	{
		name: "badge-warning-demo",
		type: "components:example",
		registryDependencies: ["badge"],
		files: ["example/badge-warning-demo.tsx"],
	},
	{
		name: "border-group-demo",
		type: "components:example",
		registryDependencies: ["border-group", "button", "menu"],
		files: ["example/border-group-demo.tsx"],
	},
	{
		name: "border-group-horizontal-demo",
		type: "components:example",
		registryDependencies: ["border-group", "button"],
		files: ["example/border-group-horizontal-demo.tsx"],
	},
	{
		name: "border-group-vertical-demo",
		type: "components:example",
		registryDependencies: ["border-group", "button"],
		files: ["example/border-group-vertical-demo.tsx"],
	},
	{
		name: "button-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-demo.tsx"],
	},
	{
		name: "button-destructive-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-destructive-demo.tsx"],
	},
	{
		name: "button-disabled-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-disabled-demo.tsx"],
	},
	{
		name: "button-ghost-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-ghost-demo.tsx"],
	},
	{
		name: "button-icon-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-icon-demo.tsx"],
	},
	{
		name: "button-info-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-info-demo.tsx"],
	},
	{
		name: "button-link-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-link-demo.tsx"],
	},
	{
		name: "button-loading-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-loading-demo.tsx"],
	},
	{
		name: "button-outline-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-outline-demo.tsx"],
	},
	{
		name: "button-secondary-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-secondary-demo.tsx"],
	},
	{
		name: "button-success-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-success-demo.tsx"],
	},
	{
		name: "button-warning-demo",
		type: "components:example",
		registryDependencies: ["button"],
		files: ["example/button-warning-demo.tsx"],
	},
	{
		name: "calendar-demo",
		type: "components:example",
		registryDependencies: ["calendar"],
		files: ["example/calendar-demo.tsx"],
	},
	{
		name: "calendar-invalid-demo",
		type: "components:example",
		registryDependencies: ["calendar"],
		files: ["example/calendar-invalid-demo.tsx"],
	},
	{
		name: "calendar-range-demo",
		type: "components:example",
		registryDependencies: ["calendar"],
		files: ["example/calendar-range-demo.tsx"],
	},
	{
		name: "calendar-multiple-demo",
		type: "components:example",
		registryDependencies: ["calendar"],
		files: ["example/calendar-multiple-demo.tsx"],
	},
	{
		name: "card-demo",
		type: "components:example",
		registryDependencies: ["card"],
		files: ["example/card-demo.tsx"],
	},
	{
		name: "card-two-demo",
		type: "components:example",
		registryDependencies: ["card"],
		files: ["example/card-two-demo.tsx"],
	},
	{
		name: "carousel-demo",
		type: "components:example",
		registryDependencies: ["carousel"],
		files: ["example/carousel-demo.tsx"],
	},
	{
		name: "carousel-left-thumb-demo",
		type: "components:example",
		registryDependencies: ["carousel"],
		files: ["example/carousel-left-thumb-demo.tsx"],
	},
	{
		name: "carousel-bottom-thumb-demo",
		type: "components:example",
		registryDependencies: ["carousel"],
		files: ["example/carousel-bottom-thumb-demo.tsx"],
	},
	{
		name: "carousel-magnifier-demo",
		type: "components:example",
		registryDependencies: ["carousel"],
		files: ["example/carousel-magnifier-demo.tsx"],
	},
	{
		name: "checkbox-group-demo",
		type: "components:example",
		registryDependencies: [
			"checkbox-group",
			"checkbox",
			"label",
			"field-error",
		],
		files: ["example/checkbox-group-demo.tsx"],
	},
	{
		name: "checkbox-group-invalid-demo",
		type: "components:example",
		registryDependencies: [
			"checkbox-group",
			"checkbox",
			"label",
			"field-error",
		],
		files: ["example/checkbox-group-invalid-demo.tsx"],
	},
	{
		name: "checkbox-group-disabled-demo",
		type: "components:example",
		registryDependencies: [
			"checkbox-group",
			"checkbox",
			"label",
			"field-error",
		],
		files: ["example/checkbox-group-disabled-demo.tsx"],
	},
	{
		name: "checkbox-group-form-demo",
		type: "components:example",
		registryDependencies: [
			"toast",
			"checkbox",
			"checkbox-group",
			"form",
			"button",
		],
		files: ["example/checkbox-group-form-demo.tsx"],
	},
	{
		name: "checkbox-demo",
		type: "components:example",
		registryDependencies: ["checkbox"],
		files: ["example/checkbox-demo.tsx"],
	},
	{
		name: "checkbox-with-text-demo",
		type: "components:example",
		registryDependencies: ["checkbox"],
		files: ["example/checkbox-with-text-demo.tsx"],
	},
	{
		name: "checkbox-disabled-demo",
		type: "components:example",
		registryDependencies: ["checkbox"],
		files: ["example/checkbox-disabled-demo.tsx"],
	},
	{
		name: "color-area-demo",
		type: "components:example",
		registryDependencies: ["color"],
		files: ["example/color-area-demo.tsx"],
	},
	{
		name: "color-slider-demo",
		type: "components:example",
		registryDependencies: ["color", "label"],
		files: ["example/color-slider-demo.tsx"],
	},
	{
		name: "color-swatch-demo",
		type: "components:example",
		registryDependencies: ["color"],
		files: ["example/color-swatch-demo.tsx"],
	},
	{
		name: "color-wheel-demo",
		type: "components:example",
		registryDependencies: ["color"],
		files: ["example/color-wheel-demo.tsx"],
	},
	{
		name: "color-field-demo",
		type: "components:example",
		registryDependencies: [
			"color",
			"color-field",
			"field-description",
			"field-error",
			"input",
			"label",
		],
		files: ["example/color-field-demo.tsx"],
	},
	{
		name: "color-field-with-form-demo",
		type: "components:example",
		registryDependencies: [
			"toast",
			"color",
			"color-field",
			"input",
			"form",
			"button",
		],
		files: ["example/color-field-with-form-demo.tsx"],
	},
	{
		name: "color-picker-demo",
		type: "components:example",
		registryDependencies: [
			"color",
			"color-field",
			"dialog",
			"button",
			"popover",
			"field-description",
			"field-error",
			"input",
			"label",
		],
		files: ["example/color-picker-demo.tsx"],
	},
	{
		name: "combo-box-demo",
		type: "components:example",
		registryDependencies: ["combo-box"],
		files: ["example/combo-box-demo.tsx"],
	},
	{
		name: "combo-box-section-demo",
		type: "components:example",
		registryDependencies: ["combo-box"],
		files: ["example/combo-box-section-demo.tsx"],
	},
	{
		name: "combo-box-async-demo",
		type: "components:example",
		registryDependencies: ["combo-box"],
		files: ["example/combo-box-async-demo.tsx"],
	},
	{
		name: "combo-box-disabled-demo",
		type: "components:example",
		registryDependencies: ["combo-box"],
		files: ["example/combo-box-disabled-demo.tsx"],
	},
	{
		name: "combo-box-with-form-demo",
		type: "components:example",
		registryDependencies: ["combo-box", "toast", "form", "button"],
		files: ["example/combo-box-with-form-demo.tsx"],
	},
	{
		name: "date-field-demo",
		type: "components:example",
		registryDependencies: [
			"label",
			"date-field",
			"field-description",
			"field-error",
		],
		files: ["example/date-field-demo.tsx"],
	},
	{
		name: "date-field-invalid-demo",
		type: "components:example",
		registryDependencies: [
			"label",
			"date-field",
			"field-description",
			"field-error",
		],
		files: ["example/date-field-invalid-demo.tsx"],
	},
	{
		name: "date-field-disabled-demo",
		type: "components:example",
		registryDependencies: [
			"label",
			"date-field",
			"field-description",
			"field-error",
		],
		files: ["example/date-field-disabled-demo.tsx"],
	},
	{
		name: "date-field-with-form-demo",
		type: "components:example",
		registryDependencies: ["date-field", "toast", "form", "button"],
		files: ["example/date-field-with-form-demo.tsx"],
	},
	{
		name: "date-picker-demo",
		type: "components:example",
		registryDependencies: ["date-picker", "calendar", "label"],
		files: ["example/date-picker-demo.tsx"],
	},
	{
		name: "date-picker-invalid-demo",
		type: "components:example",
		registryDependencies: ["date-picker", "calendar", "label"],
		files: ["example/date-picker-invalid-demo.tsx"],
	},
	{
		name: "date-picker-disabled-demo",
		type: "components:example",
		registryDependencies: ["date-picker", "calendar", "label"],
		files: ["example/date-picker-disabled-demo.tsx"],
	},
	{
		name: "date-picker-unavailable-dates-demo",
		type: "components:example",
		registryDependencies: ["date-picker", "calendar", "label"],
		files: ["example/date-picker-unavailable-dates-demo.tsx"],
	},
	{
		name: "date-picker-presets-demo",
		type: "components:example",
		registryDependencies: ["date-picker", "calendar", "label"],
		files: ["example/date-picker-presets-demo.tsx"],
	},
	{
		name: "date-picker-pick-date-error-demo",
		type: "components:example",
		registryDependencies: ["date-picker", "calendar", "label"],
		files: ["example/date-picker-pick-date-error-demo.tsx"],
	},
	{
		name: "date-picker-range-demo",
		type: "components:example",
		registryDependencies: ["date-picker", "calendar", "label"],
		files: ["example/date-picker-range-demo.tsx"],
	},
	{
		name: "date-picker-with-form-demo",
		type: "components:example",
		registryDependencies: [
			"date-picker",
			"calendar",
			"toast",
			"form",
			"button",
		],
		files: ["example/date-picker-with-form-demo.tsx"],
	},
	{
		name: "date-picker-range-with-form-demo",
		type: "components:example",
		registryDependencies: [
			"date-picker",
			"calendar",
			"toast",
			"form",
			"button",
		],
		files: ["example/date-picker-range-with-form-demo.tsx"],
	},
	{
		name: "dialog-demo",
		type: "components:example",
		registryDependencies: ["dialog", "button", "input", "label"],
		files: ["example/dialog-demo.tsx"],
	},
	{
		name: "dialog-non-dismissable-demo",
		type: "components:example",
		registryDependencies: ["dialog", "button", "input", "label"],
		files: ["example/dialog-non-dismissable-demo.tsx"],
	},
	{
		name: "dialog-alert-demo",
		type: "components:example",
		registryDependencies: ["dialog", "button"],
		files: ["example/dialog-alert-demo.tsx"],
	},
	{
		name: "dialog-menu-demo",
		type: "components:example",
		registryDependencies: ["dialog", "menu", "button"],
		files: ["example/dialog-menu-demo.tsx"],
	},
	{
		name: "drawer-demo",
		type: "components:example",
		registryDependencies: ["dialog", "button"],
		files: ["example/drawer-demo.tsx"],
	},
	{
		name: "drawer-long-content-demo",
		type: "components:example",
		registryDependencies: ["dialog", "button"],
		files: ["example/drawer-long-content-demo.tsx"],
	},
	{
		name: "drawer-responsive-demo",
		type: "components:example",
		registryDependencies: ["responsive-dialog-drawer"],
		files: ["example/drawer-responsive-demo.tsx"],
	},
	{
		name: "field-description-demo",
		type: "components:example",
		registryDependencies: [
			"text-field",
			"input",
			"label",
			"field-description",
		],
		files: ["example/field-description-demo.tsx"],
	},
	{
		name: "field-error-demo",
		type: "components:example",
		registryDependencies: [
			"text-field",
			"input",
			"label",
			"field-description",
			"field-error",
		],
		files: ["example/field-error-demo.tsx"],
	},
	{
		name: "file-trigger-demo",
		type: "components:example",
		registryDependencies: ["file-trigger", "button"],
		files: ["example/file-trigger-demo.tsx"],
	},
	{
		name: "file-trigger-directory-demo",
		type: "components:example",
		registryDependencies: ["file-trigger", "button"],
		files: ["example/file-trigger-directory-demo.tsx"],
	},
	{
		name: "file-trigger-multiple-demo",
		type: "components:example",
		registryDependencies: ["file-trigger", "button"],
		files: ["example/file-trigger-multiple-demo.tsx"],
	},
	{
		name: "file-trigger-media-capture-demo",
		type: "components:example",
		registryDependencies: ["file-trigger", "button"],
		files: ["example/file-trigger-media-capture-demo.tsx"],
	},
];
