import type { Metadata, Viewport } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { QueryClientProvider } from "@/components/query-client-provider";
import { RouterProvider } from "@/components/router-provider";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import { ToastProvider } from "@/registry/ui/toast";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
	// Also supported by less commonly used
	// interactiveWidget: 'resizes-visual',
};

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased",
					fontSans.variable,
				)}
			>
				<QueryClientProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<RouterProvider>
							<ToastProvider>
								<div>
									<SiteHeader />
									<main>{children}</main>
									<SiteFooter />
								</div>
							</ToastProvider>
						</RouterProvider>
					</ThemeProvider>
				</QueryClientProvider>
			</body>
		</html>
	);
}
