import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { ModeToggle } from "@/components/dark-mode-toggle";
import { QueryClientProvider } from "@/components/query-client-provider";
import { RouterProvider } from "@/components/router-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { ToastProvider } from "@/components/ui/toast";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased",
					fontSans.variable,
				)}
			>
				<QueryClientProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<RouterProvider>
							<ToastProvider>
								<main>
									<div className="container pt-8">
										<ModeToggle />
									</div>
									{children}
								</main>
							</ToastProvider>
						</RouterProvider>
					</ThemeProvider>
				</QueryClientProvider>
			</body>
		</html>
	);
}
